### PR TITLE
Fix scrape_procedure

### PR DESCRIPTION
**Pull request by k-stewart**
* Update Nokogiri finders to current state of eff.org/about/staff
* Create a helper to derive team from title, since the staff directory no longer includes team name
* remove unnecessary code

### CODE REVIEW

**Comment by vbrown608** [comment]
The way we scraped teams previously was to output them in the Kittens view but visually hide them. Using rendered HTML as an API isn't ideal but this approach does seem brittle as we have titles like  "Extraordinaire" (and leez used to be "Bit Flipper"). 

We could update the new Kittens view to output (and hide) the team.

**Comment by k-stewart** [comment]
Closing this in favor of that.

**Comment by k-stewart** [comment]
Update: will reopen for the other refactors after that code is returned to Kittens

**Comment by k-stewart** [comment]
Further update: I probably won't actually do that

**Pull request closed without merging**
